replicaCount: 1

image:
  repository: tutum/hello-world
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

app:
  containerPort: 80 # 8080
  healthCheckPath: /
  environment: {}
  autoscaling:
    enabled: true
    # maxReplicas: 2
    # minReplicas: 1
    # targetCPUUtilizationPercentage: 40

secrets: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  # annotations: {}
  # path: /
  # tls: []

resources:
  constraints: 
    enabled: false
  requests:
    cpu: 500m