{{ if gt (len .Values.secrets) 0 }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-chart.fullname" . }}
  type: Opaque
  labels:
    app: {{ include "app-chart.name" . }}
    chart: {{ include "app-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $key, $val := .Values.secrets }}
    {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{ end }}